defaults:
  - ppo_megatron_trainer
  - _self_

actor_rollout_ref:
  model:
    trust_remote_code: False
    use_fused_kernels: False
    use_remove_padding: False
  rollout:
    quantization: null
    layer_name_map:
      qkv_layer_name: qkv
      gate_proj_layer_name: gate_up

data:
  image_patch_size: 16

reward:
  custom_reward_function:
    path: pkg://verl/utils/reward_score/short_cot_qwen
    name: compute_score_qwen_gpt_step_bonus
    reward_kwargs: {}
